fix: do not allow non-negative page parameter
prevent a negative slicing ValueError in search.py

```
ValueError: Search does not support negative slicing.
(3 additional frame(s) were not displayed)
...
  File "home/views.py", line 431, in get_context_data
    results, total = search.search(query, start=(page - 1) * 10)
  File "home/search.py", line 178, in search
    response = s[start : start + size].execute()
```