fix: pin redis client to 4.4.2
there's a regression in 4.5 that causes all redis cache usage to fail

```
File /usr/local/lib/python3.10/dist-packages/redis/client.py:1234, in Redis._send_command_parse_response(self, conn, command_name, *args, **options)
   1230 def _send_command_parse_response(self, conn, command_name, *args, **options):
   1231     """
   1232     Send a command and parse the response
   1233     """
-> 1234     conn.send_command(*args)
   1235     return self.parse_response(conn, command_name, **options)

File /usr/local/lib/python3.10/dist-packages/redis/connection.py:916, in Connection.send_command(self, *args, **kwargs)
    913 def send_command(self, *args, **kwargs):
    914     """Pack and send a command to the Redis server"""
    915     self.send_packed_command(
--> 916         self._command_packer.pack(*args),
    917         check_health=kwargs.get("check_health", True),
    918     )

AttributeError: 'UnixDomainSocketConnection' object has no attribute '_command_packer'
```